In [95]:
import pandas as pd

In [96]:
df = pd.read_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_raw\Detailed_Statistics_Departures_DTW.csv",skiprows=7)

In [97]:
df.head(20)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,DL,01/01/2025,307.0,N813NW,HNL,10:00,10:59,598.0,615.0,59.0,11:21,22.0,59.0,0.0,17.0,0.0,0.0
1,DL,01/01/2025,334.0,N392DN,LAS,09:15,09:09,273.0,259.0,-6.0,09:19,10.0,0.0,0.0,0.0,0.0,0.0
2,DL,01/01/2025,349.0,N350DN,SAN,12:40,12:37,296.0,294.0,-3.0,12:59,22.0,0.0,0.0,0.0,0.0,0.0
3,DL,01/01/2025,361.0,N859DN,SFO,08:35,08:31,320.0,327.0,-4.0,09:00,29.0,0.0,0.0,0.0,0.0,0.0
4,DL,01/01/2025,369.0,N377DN,SAN,16:15,16:17,295.0,303.0,2.0,16:49,32.0,0.0,0.0,0.0,0.0,0.0
5,DL,01/01/2025,411.0,N894DN,SRQ,08:37,09:37,171.0,173.0,60.0,10:02,25.0,60.0,0.0,2.0,0.0,0.0
6,DL,01/01/2025,442.0,N899DN,SFO,16:30,18:24,309.0,329.0,114.0,18:53,29.0,114.0,0.0,20.0,0.0,0.0
7,DL,01/01/2025,469.0,N897DN,SFO,12:35,12:35,313.0,321.0,0.0,13:01,26.0,0.0,0.0,0.0,0.0,0.0
8,DL,01/01/2025,492.0,N353DN,SAN,08:35,08:42,307.0,310.0,7.0,09:17,35.0,0.0,0.0,0.0,0.0,0.0
9,DL,01/01/2025,565.0,N334DN,SEA,20:30,21:07,328.0,306.0,37.0,21:35,28.0,15.0,0.0,0.0,0.0,0.0
10,DL,01/01/2025,694.0,N378DN,LAX,20:45,21:01,313.0,306.0,16.0,21:20,19.0,0.0,0.0,0.0,0.0,0.0
11,DL,01/01/2025,698.0,N126DN,SLC,08:10,08:20,260.0,251.0,10.0,08:49,29.0,0.0,0.0,0.0,0.0,0.0
12,DL,01/01/2025,719.0,N593NW,RSW,10:22,10:26,175.0,179.0,4.0,10:54,28.0,0.0,0.0,0.0,0.0,0.0
13,DL,01/01/2025,728.0,N883DN,SEA,12:34,12:58,311.0,305.0,24.0,13:23,25.0,18.0,0.0,0.0,0.0,0.0
14,DL,01/01/2025,734.0,N378DN,SEA,08:25,08:33,320.0,306.0,8.0,09:01,28.0,0.0,0.0,0.0,0.0,0.0
15,DL,01/01/2025,765.0,N310DN,SLC,17:59,17:58,255.0,250.0,-1.0,18:24,26.0,0.0,0.0,0.0,0.0,0.0
16,DL,01/01/2025,766.0,N894DN,LAS,16:25,17:03,264.0,270.0,38.0,17:19,16.0,0.0,0.0,6.0,0.0,38.0
17,DL,01/01/2025,769.0,N940AT,MSN,20:20,20:28,83.0,88.0,8.0,20:55,27.0,0.0,0.0,0.0,0.0,0.0
18,DL,01/01/2025,788.0,N316NB,SAT,08:38,08:30,209.0,201.0,-8.0,08:41,11.0,0.0,0.0,0.0,0.0,0.0
19,DL,01/01/2025,794.0,N586NW,LAX,08:36,09:41,302.0,315.0,65.0,10:17,36.0,65.0,0.0,13.0,0.0,0.0

In [98]:
print(df.isna())

       Carrier Code  Date (MM/DD/YYYY)  Flight Number  Tail Number  \
0             False              False          False        False
1             False              False          False        False
2             False              False          False        False
3             False              False          False        False
4             False              False          False        False
...             ...                ...            ...          ...
59206         False              False          False        False
59207         False              False          False        False
59208         False              False          False        False
59209         False              False          False        False
59210         False               True           True         True

       Destination Airport  Scheduled departure time  Actual departure time  \
0                    False                     False                  False
1                    False                     False                  False
2                    False                     False                  False
3                    False                     False                  False
4                    False                     False                  False
...                    ...                       ...                    ...
59206                False                     False                  False
59207                False                     False                  False
59208                False                     False                  False
59209                False                     False                  False
59210                 True                      True                   True

       Scheduled elapsed time (Minutes)  Actual elapsed time (Minutes)  \
0                                 False                          False
1                                 False                          False
2                                 False                          False
3                                 False                          False
4                                 False                          False
...                                 ...                            ...
59206                             False                          False
59207                             False                          False
59208                             False                          False
59209                             False                          False
59210                              True                           True

       Departure delay (Minutes)  Wheels-off time  Taxi-Out time (Minutes)  \
0                          False            False                    False
1                          False            False                    False
2                          False            False                    False
3                          False            False                    False
4                          False            False                    False
...                          ...              ...                      ...
59206                      False            False                    False
59207                      False            False                    False
59208                      False            False                    False
59209                      False            False                    False
59210                       True             True                     True

       Delay Carrier (Minutes)  Delay Weather (Minutes)  \
0                        False                    False
1                        False                    False
2                        False                    False
3                        False                    False
4                        False                    False
...                        ...                      ...
59206                    False                    False
59207                    False                    False
59208                    False                    False
59209                    False                    False
59210                     True                     True

       Delay National Aviation System (Minutes)  Delay Security (Minutes)  \
0                                         False                     False
1                                         False                     False
2                                         False                     False
3                                         False                     False
4                                         False                     False
...                                         ...                       ...
59206                                     False                     False
59207                                     False                     False
59208                                     False                     False
59209                                     False                     False
59210                                      True                      True

       Delay Late Aircraft Arrival (Minutes)
0                                      False
1                                      False
2                                      False
3                                      False
4                                      False
...                                      ...
59206                                  False
59207                                  False
59208                                  False
59209                                  False
59210                                   True

[59211 rows x 17 columns]

In [99]:
df = df.drop(59210)
print(df.isna())

       Carrier Code  Date (MM/DD/YYYY)  Flight Number  Tail Number  \
0             False              False          False        False
1             False              False          False        False
2             False              False          False        False
3             False              False          False        False
4             False              False          False        False
...             ...                ...            ...          ...
59205         False              False          False        False
59206         False              False          False        False
59207         False              False          False        False
59208         False              False          False        False
59209         False              False          False        False

       Destination Airport  Scheduled departure time  Actual departure time  \
0                    False                     False                  False
1                    False                     False                  False
2                    False                     False                  False
3                    False                     False                  False
4                    False                     False                  False
...                    ...                       ...                    ...
59205                False                     False                  False
59206                False                     False                  False
59207                False                     False                  False
59208                False                     False                  False
59209                False                     False                  False

       Scheduled elapsed time (Minutes)  Actual elapsed time (Minutes)  \
0                                 False                          False
1                                 False                          False
2                                 False                          False
3                                 False                          False
4                                 False                          False
...                                 ...                            ...
59205                             False                          False
59206                             False                          False
59207                             False                          False
59208                             False                          False
59209                             False                          False

       Departure delay (Minutes)  Wheels-off time  Taxi-Out time (Minutes)  \
0                          False            False                    False
1                          False            False                    False
2                          False            False                    False
3                          False            False                    False
4                          False            False                    False
...                          ...              ...                      ...
59205                      False            False                    False
59206                      False            False                    False
59207                      False            False                    False
59208                      False            False                    False
59209                      False            False                    False

       Delay Carrier (Minutes)  Delay Weather (Minutes)  \
0                        False                    False
1                        False                    False
2                        False                    False
3                        False                    False
4                        False                    False
...                        ...                      ...
59205                    False                    False
59206                    False                    False
59207                    False                    False
59208                    False                    False
59209                    False                    False

       Delay National Aviation System (Minutes)  Delay Security (Minutes)  \
0                                         False                     False
1                                         False                     False
2                                         False                     False
3                                         False                     False
4                                         False                     False
...                                         ...                       ...
59205                                     False                     False
59206                                     False                     False
59207                                     False                     False
59208                                     False                     False
59209                                     False                     False

       Delay Late Aircraft Arrival (Minutes)
0                                      False
1                                      False
2                                      False
3                                      False
4                                      False
...                                      ...
59205                                  False
59206                                  False
59207                                  False
59208                                  False
59209                                  False

[59210 rows x 17 columns]

In [100]:
df.head(10)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,DL,01/01/2025,307.0,N813NW,HNL,10:00,10:59,598.0,615.0,59.0,11:21,22.0,59.0,0.0,17.0,0.0,0.0
1,DL,01/01/2025,334.0,N392DN,LAS,09:15,09:09,273.0,259.0,-6.0,09:19,10.0,0.0,0.0,0.0,0.0,0.0
2,DL,01/01/2025,349.0,N350DN,SAN,12:40,12:37,296.0,294.0,-3.0,12:59,22.0,0.0,0.0,0.0,0.0,0.0
3,DL,01/01/2025,361.0,N859DN,SFO,08:35,08:31,320.0,327.0,-4.0,09:00,29.0,0.0,0.0,0.0,0.0,0.0
4,DL,01/01/2025,369.0,N377DN,SAN,16:15,16:17,295.0,303.0,2.0,16:49,32.0,0.0,0.0,0.0,0.0,0.0
5,DL,01/01/2025,411.0,N894DN,SRQ,08:37,09:37,171.0,173.0,60.0,10:02,25.0,60.0,0.0,2.0,0.0,0.0
6,DL,01/01/2025,442.0,N899DN,SFO,16:30,18:24,309.0,329.0,114.0,18:53,29.0,114.0,0.0,20.0,0.0,0.0
7,DL,01/01/2025,469.0,N897DN,SFO,12:35,12:35,313.0,321.0,0.0,13:01,26.0,0.0,0.0,0.0,0.0,0.0
8,DL,01/01/2025,492.0,N353DN,SAN,08:35,08:42,307.0,310.0,7.0,09:17,35.0,0.0,0.0,0.0,0.0,0.0
9,DL,01/01/2025,565.0,N334DN,SEA,20:30,21:07,328.0,306.0,37.0,21:35,28.0,15.0,0.0,0.0,0.0,0.0

In [101]:
df.columns = [ 
    "carrier_code",
    "flight_date",
    "flight_number",
    "tail_number",
    "destination_airport",
    "scheduled_departure_time",
    "actual_departure_time",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "wheels_off_time",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59210 entries, 0 to 59209
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              59210 non-null  object
 1   flight_date               59210 non-null  object
 2   flight_number             59210 non-null  float64
 3   tail_number               59210 non-null  object
 4   destination_airport       59210 non-null  object
 5   scheduled_departure_time  59210 non-null  object
 6   actual_departure_time     59210 non-null  object
 7   scheduled_elapsed_time    59210 non-null  float64
 8   actual_elapsed_time       59210 non-null  float64
 9   departure_delay           59210 non-null  float64
 10  wheels_off_time           59210 non-null  object
 11  taxi_out_time             59210 non-null  float64
 12  delay_carrier             59210 non-null  float64
 13  delay_weather             59210 non-null  float64
 14  delay_nas                 59210 non-null  float64
 15  delay_security            59210 non-null  float64
 16  delay_late_aircraft       59210 non-null  float64
dtypes: float64(10), object(7)
memory usage: 7.7+ MB

In [103]:
df["flight_date"] = pd.to_datetime(df["flight_date"], format = "%m/%d/%Y")

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59210 entries, 0 to 59209
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              59210 non-null  object
 1   flight_date               59210 non-null  datetime64[ns]
 2   flight_number             59210 non-null  float64
 3   tail_number               59210 non-null  object
 4   destination_airport       59210 non-null  object
 5   scheduled_departure_time  59210 non-null  object
 6   actual_departure_time     59210 non-null  object
 7   scheduled_elapsed_time    59210 non-null  float64
 8   actual_elapsed_time       59210 non-null  float64
 9   departure_delay           59210 non-null  float64
 10  wheels_off_time           59210 non-null  object
 11  taxi_out_time             59210 non-null  float64
 12  delay_carrier             59210 non-null  float64
 13  delay_weather             59210 non-null  float64
 14  delay_nas                 59210 non-null  float64
 15  delay_security            59210 non-null  float64
 16  delay_late_aircraft       59210 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(6)
memory usage: 7.7+ MB

In [105]:
time_cols = [
    "scheduled_departure_time",
    "actual_departure_time",
    "wheels_off_time"
]
for cols in time_cols:
    df[cols] = df[cols].astype(str).str.strip()
    df[cols] = df[cols].replace("24:00:00","00:00:00")
    df[cols] = df[cols].replace("24:00","00:00:00")
    df[cols] = df[cols].apply( lambda x: "0" + x if len(x) == 4 else x)
    df[cols] = df[cols].apply( lambda x: x + ":00" if len(x) == 5 else x)
    df[cols] = pd.to_datetime(df[cols], format = "%H:%M:%S", errors = "coerce")

In [106]:
df[time_cols].isna().sum()
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,2025-01-01,307.0,N813NW,HNL,1900-01-01 10:00:00,1900-01-01 10:59:00,598.0,615.0,59.0,1900-01-01 11:21:00,22.0,59.0,0.0,17.0,0.0,0.0
1,DL,2025-01-01,334.0,N392DN,LAS,1900-01-01 09:15:00,1900-01-01 09:09:00,273.0,259.0,-6.0,1900-01-01 09:19:00,10.0,0.0,0.0,0.0,0.0,0.0
2,DL,2025-01-01,349.0,N350DN,SAN,1900-01-01 12:40:00,1900-01-01 12:37:00,296.0,294.0,-3.0,1900-01-01 12:59:00,22.0,0.0,0.0,0.0,0.0,0.0
3,DL,2025-01-01,361.0,N859DN,SFO,1900-01-01 08:35:00,1900-01-01 08:31:00,320.0,327.0,-4.0,1900-01-01 09:00:00,29.0,0.0,0.0,0.0,0.0,0.0
4,DL,2025-01-01,369.0,N377DN,SAN,1900-01-01 16:15:00,1900-01-01 16:17:00,295.0,303.0,2.0,1900-01-01 16:49:00,32.0,0.0,0.0,0.0,0.0,0.0

In [107]:
df["flight_date"] = df["flight_date"].dt.strftime("%Y-%m-%d")
for cols in time_cols:
    df[cols] = df[cols].dt.strftime("%H:%M:%S")

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59210 entries, 0 to 59209
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              59210 non-null  object
 1   flight_date               59210 non-null  object
 2   flight_number             59210 non-null  float64
 3   tail_number               59210 non-null  object
 4   destination_airport       59210 non-null  object
 5   scheduled_departure_time  59210 non-null  object
 6   actual_departure_time     59210 non-null  object
 7   scheduled_elapsed_time    59210 non-null  float64
 8   actual_elapsed_time       59210 non-null  float64
 9   departure_delay           59210 non-null  float64
 10  wheels_off_time           59210 non-null  object
 11  taxi_out_time             59210 non-null  float64
 12  delay_carrier             59210 non-null  float64
 13  delay_weather             59210 non-null  float64
 14  delay_nas                 59210 non-null  float64
 15  delay_security            59210 non-null  float64
 16  delay_late_aircraft       59210 non-null  float64
dtypes: float64(10), object(7)
memory usage: 7.7+ MB

In [110]:
float_cols = [
    "flight_number",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]
for cols in float_cols:
    df[cols] = df[cols].astype(int)

In [112]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,2025-01-01,307,N813NW,HNL,10:00:00,10:59:00,598,615,59,11:21:00,22,59,0,17,0,0
1,DL,2025-01-01,334,N392DN,LAS,09:15:00,09:09:00,273,259,-6,09:19:00,10,0,0,0,0,0
2,DL,2025-01-01,349,N350DN,SAN,12:40:00,12:37:00,296,294,-3,12:59:00,22,0,0,0,0,0
3,DL,2025-01-01,361,N859DN,SFO,08:35:00,08:31:00,320,327,-4,09:00:00,29,0,0,0,0,0
4,DL,2025-01-01,369,N377DN,SAN,16:15:00,16:17:00,295,303,2,16:49:00,32,0,0,0,0,0

In [115]:
df.to_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_clean\dtw_cleaned.csv",index=False)