In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_raw\Detailed_Statistics_Departures_JFK.csv",skiprows=6)

In [9]:
df.tail(10)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
30451,DL,12/31/2025,2320.0,N346NB,RSW,07:18,07:20,204.0,184.0,2.0,07:44,24.0,0.0,0.0,0.0,0.0,0.0
30452,DL,12/31/2025,2342.0,N710TW,ATL,12:59,13:12,154.0,144.0,13.0,13:35,23.0,0.0,0.0,0.0,0.0,0.0
30453,DL,12/31/2025,2390.0,N338NW,MSP,07:30,07:48,200.0,184.0,18.0,08:03,15.0,0.0,0.0,0.0,0.0,0.0
30454,DL,12/31/2025,2414.0,N820DN,MSP,11:55,12:39,195.0,200.0,44.0,12:56,17.0,0.0,0.0,5.0,0.0,44.0
30455,DL,12/31/2025,2500.0,N372DA,MIA,15:00,15:12,202.0,182.0,12.0,15:36,24.0,0.0,0.0,0.0,0.0,0.0
30456,DL,12/31/2025,2506.0,N344NB,AUS,07:00,06:53,268.0,229.0,-7.0,07:06,13.0,0.0,0.0,0.0,0.0,0.0
30457,DL,12/31/2025,2521.0,N135DQ,SRQ,08:25,08:18,197.0,185.0,-7.0,08:44,26.0,0.0,0.0,0.0,0.0,0.0
30458,DL,12/31/2025,2560.0,N580DT,LAS,16:59,16:57,351.0,336.0,-2.0,17:15,18.0,0.0,0.0,0.0,0.0,0.0
30459,DL,12/31/2025,2775.0,N813DN,MCO,11:50,11:50,178.0,155.0,0.0,12:02,12.0,0.0,0.0,0.0,0.0,0.0
30460,SOURCE: Bureau of Transportation Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.isna()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30456,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30457,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30458,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30459,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30460,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [10]:
df = df.drop(30460)

In [11]:
df.tail(10)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
30450,DL,12/31/2025,2293.0,N601DT,ATL,21:15,21:58,166.0,134.0,43.0,22:20,22.0,0.0,0.0,0.0,0.0,0.0
30451,DL,12/31/2025,2320.0,N346NB,RSW,07:18,07:20,204.0,184.0,2.0,07:44,24.0,0.0,0.0,0.0,0.0,0.0
30452,DL,12/31/2025,2342.0,N710TW,ATL,12:59,13:12,154.0,144.0,13.0,13:35,23.0,0.0,0.0,0.0,0.0,0.0
30453,DL,12/31/2025,2390.0,N338NW,MSP,07:30,07:48,200.0,184.0,18.0,08:03,15.0,0.0,0.0,0.0,0.0,0.0
30454,DL,12/31/2025,2414.0,N820DN,MSP,11:55,12:39,195.0,200.0,44.0,12:56,17.0,0.0,0.0,5.0,0.0,44.0
30455,DL,12/31/2025,2500.0,N372DA,MIA,15:00,15:12,202.0,182.0,12.0,15:36,24.0,0.0,0.0,0.0,0.0,0.0
30456,DL,12/31/2025,2506.0,N344NB,AUS,07:00,06:53,268.0,229.0,-7.0,07:06,13.0,0.0,0.0,0.0,0.0,0.0
30457,DL,12/31/2025,2521.0,N135DQ,SRQ,08:25,08:18,197.0,185.0,-7.0,08:44,26.0,0.0,0.0,0.0,0.0,0.0
30458,DL,12/31/2025,2560.0,N580DT,LAS,16:59,16:57,351.0,336.0,-2.0,17:15,18.0,0.0,0.0,0.0,0.0,0.0
30459,DL,12/31/2025,2775.0,N813DN,MCO,11:50,11:50,178.0,155.0,0.0,12:02,12.0,0.0,0.0,0.0,0.0,0.0

In [16]:
print(df.duplicated().sum())

0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30460 entries, 0 to 30459
Data columns (total 17 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Carrier Code                              30460 non-null  object
 1   Date (MM/DD/YYYY)                         30460 non-null  object
 2   Flight Number                             30460 non-null  float64
 3   Tail Number                               30460 non-null  object
 4   Destination Airport                       30460 non-null  object
 5   Scheduled departure time                  30460 non-null  object
 6   Actual departure time                     30460 non-null  object
 7   Scheduled elapsed time (Minutes)          30460 non-null  float64
 8   Actual elapsed time (Minutes)             30460 non-null  float64
 9   Departure delay (Minutes)                 30460 non-null  float64
 10  Wheels-off time                           30460 non-null  object
 11  Taxi-Out time (Minutes)                   30460 non-null  float64
 12  Delay Carrier (Minutes)                   30460 non-null  float64
 13  Delay Weather (Minutes)                   30460 non-null  float64
 14  Delay National Aviation System (Minutes)  30460 non-null  float64
 15  Delay Security (Minutes)                  30460 non-null  float64
 16  Delay Late Aircraft Arrival (Minutes)     30460 non-null  float64
dtypes: float64(10), object(7)
memory usage: 4.0+ MB

In [19]:
df.columns = [
    "carrier_code",
    "flight_date",
    "flight_number",
    "tail_number",
    "destination_airport",
    "scheduled_departure_time",
    "actual_departure_time",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "wheels_off_time",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]

In [20]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,01/01/2025,305.0,N3758Y,FLL,11:15,11:08,187.0,201.0,-7.0,11:24,16.0,0.0,0.0,0.0,0.0,0.0
1,DL,01/01/2025,315.0,N329DN,SLC,17:45,17:42,332.0,324.0,-3.0,18:19,37.0,0.0,0.0,0.0,0.0,0.0
2,DL,01/01/2025,356.0,N109DU,DFW,08:30,11:41,260.0,260.0,191.0,12:01,20.0,0.0,0.0,0.0,0.0,191.0
3,DL,01/01/2025,403.0,N521DT,LAS,11:30,11:26,357.0,336.0,-4.0,11:45,19.0,0.0,0.0,0.0,0.0,0.0
4,DL,01/01/2025,416.0,N528DE,LAS,16:55,17:15,356.0,347.0,20.0,17:44,29.0,0.0,0.0,0.0,0.0,0.0

In [24]:
df["flight_date"] = pd.to_datetime(df["flight_date"],format="%m/%d/%Y")

In [27]:
time_cols = [
    "scheduled_departure_time",
    "actual_departure_time",
    "wheels_off_time"
]
for cols in time_cols:
    df[cols] = df[cols].replace("24:00","00:00:00")
    df[cols] = df[cols].replace("24:00:00","00:00:00")
    df[cols] = df[cols].apply(lambda x: "0" + x if len(x) == 4 else x)
    df[cols] = df[cols].apply(lambda x: x + ":00" if len(x) == 5 else x)
    df[cols] = pd.to_datetime(df[cols],format="%H:%M:%S")

In [29]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,2025-01-01,305.0,N3758Y,FLL,1900-01-01 11:15:00,1900-01-01 11:08:00,187.0,201.0,-7.0,1900-01-01 11:24:00,16.0,0.0,0.0,0.0,0.0,0.0
1,DL,2025-01-01,315.0,N329DN,SLC,1900-01-01 17:45:00,1900-01-01 17:42:00,332.0,324.0,-3.0,1900-01-01 18:19:00,37.0,0.0,0.0,0.0,0.0,0.0
2,DL,2025-01-01,356.0,N109DU,DFW,1900-01-01 08:30:00,1900-01-01 11:41:00,260.0,260.0,191.0,1900-01-01 12:01:00,20.0,0.0,0.0,0.0,0.0,191.0
3,DL,2025-01-01,403.0,N521DT,LAS,1900-01-01 11:30:00,1900-01-01 11:26:00,357.0,336.0,-4.0,1900-01-01 11:45:00,19.0,0.0,0.0,0.0,0.0,0.0
4,DL,2025-01-01,416.0,N528DE,LAS,1900-01-01 16:55:00,1900-01-01 17:15:00,356.0,347.0,20.0,1900-01-01 17:44:00,29.0,0.0,0.0,0.0,0.0,0.0

In [33]:
df["flight_date"] = df["flight_date"].dt.strftime("%Y-%m-%d")

for cols in time_cols:
    df[cols] = df[cols].dt.strftime("%H:%M:%S")

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30460 entries, 0 to 30459
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              30460 non-null  object
 1   flight_date               30460 non-null  object
 2   flight_number             30460 non-null  float64
 3   tail_number               30460 non-null  object
 4   destination_airport       30460 non-null  object
 5   scheduled_departure_time  30460 non-null  object
 6   actual_departure_time     30460 non-null  object
 7   scheduled_elapsed_time    30460 non-null  float64
 8   actual_elapsed_time       30460 non-null  float64
 9   departure_delay           30460 non-null  float64
 10  wheels_off_time           30460 non-null  object
 11  taxi_out_time             30460 non-null  float64
 12  delay_carrier             30460 non-null  float64
 13  delay_weather             30460 non-null  float64
 14  delay_nas                 30460 non-null  float64
 15  delay_security            30460 non-null  float64
 16  delay_late_aircraft       30460 non-null  float64
dtypes: float64(10), object(7)
memory usage: 4.0+ MB

In [36]:
float_cols = [
    "flight_number",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]
for cols in float_cols:
    df[cols] = df[cols].astype(int)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30460 entries, 0 to 30459
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              30460 non-null  object
 1   flight_date               30460 non-null  object
 2   flight_number             30460 non-null  int64
 3   tail_number               30460 non-null  object
 4   destination_airport       30460 non-null  object
 5   scheduled_departure_time  30460 non-null  object
 6   actual_departure_time     30460 non-null  object
 7   scheduled_elapsed_time    30460 non-null  int64
 8   actual_elapsed_time       30460 non-null  int64
 9   departure_delay           30460 non-null  int64
 10  wheels_off_time           30460 non-null  object
 11  taxi_out_time             30460 non-null  int64
 12  delay_carrier             30460 non-null  int64
 13  delay_weather             30460 non-null  int64
 14  delay_nas                 30460 non-null  int64
 15  delay_security            30460 non-null  int64
 16  delay_late_aircraft       30460 non-null  int64
dtypes: int64(10), object(7)
memory usage: 4.0+ MB

In [39]:
df.to_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_clean\jfk_cleaned.csv",index=False)