In [22]:
import pandas as pd

In [23]:
df = pd.read_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_raw\Detailed_Statistics_Departures_LAX.csv", skiprows=6)

In [24]:
df.head(10)
df.tail(10)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
36427,DL,12/31/2025,2653.0,N364NB,LAS,22:30,22:25,82.0,74.0,-5.0,22:38,13.0,0.0,0.0,0.0,0.0,0.0
36428,DL,12/31/2025,2766.0,N386DA,PDX,10:00,09:50,155.0,137.0,-10.0,10:14,24.0,0.0,0.0,0.0,0.0,0.0
36429,DL,12/31/2025,2828.0,N369NB,DEN,08:46,08:42,149.0,144.0,-4.0,09:10,28.0,0.0,0.0,0.0,0.0,0.0
36430,DL,12/31/2025,2906.0,N509DT,SLC,05:30,05:26,125.0,100.0,-4.0,05:40,14.0,0.0,0.0,0.0,0.0,0.0
36431,DL,12/31/2025,2975.0,N366NB,PDX,08:25,08:12,156.0,125.0,-13.0,08:25,13.0,0.0,0.0,0.0,0.0,0.0
36432,DL,12/31/2025,2980.0,N3744F,SEA,07:40,07:36,185.0,154.0,-4.0,07:49,13.0,0.0,0.0,0.0,0.0,0.0
36433,DL,12/31/2025,2986.0,N3743H,SFO,21:20,21:17,90.0,97.0,-3.0,21:38,21.0,0.0,0.0,0.0,0.0,0.0
36434,DL,12/31/2025,8805.0,N860DN,DTW,13:25,13:16,267.0,260.0,-9.0,13:31,15.0,0.0,0.0,0.0,0.0,0.0
36435,DL,12/31/2025,8810.0,N828DN,ATL,13:30,13:33,252.0,245.0,3.0,13:57,24.0,0.0,0.0,0.0,0.0,0.0
36436,SOURCE: Bureau of Transportation Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df = df.drop(36436)

In [26]:
print(df.duplicated().sum())
print(df.isna().sum())

0
Carrier Code                                0
Date (MM/DD/YYYY)                           0
Flight Number                               0
Tail Number                                 0
Destination Airport                         0
Scheduled departure time                    0
Actual departure time                       0
Scheduled elapsed time (Minutes)            0
Actual elapsed time (Minutes)               0
Departure delay (Minutes)                   0
Wheels-off time                             0
Taxi-Out time (Minutes)                     0
Delay Carrier (Minutes)                     0
Delay Weather (Minutes)                     0
Delay National Aviation System (Minutes)    0
Delay Security (Minutes)                    0
Delay Late Aircraft Arrival (Minutes)       0
dtype: int64

In [27]:
df.columns = [
    "carrier_code",
    "flight_date",
    "flight_number",
    "tail_number",
    "destination_airport",
    "scheduled_departure_time",
    "actual_departure_time",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "wheels_off_time",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36436 entries, 0 to 36435
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              36436 non-null  object
 1   flight_date               36436 non-null  object
 2   flight_number             36436 non-null  float64
 3   tail_number               36436 non-null  object
 4   destination_airport       36436 non-null  object
 5   scheduled_departure_time  36436 non-null  object
 6   actual_departure_time     36436 non-null  object
 7   scheduled_elapsed_time    36436 non-null  float64
 8   actual_elapsed_time       36436 non-null  float64
 9   departure_delay           36436 non-null  float64
 10  wheels_off_time           36436 non-null  object
 11  taxi_out_time             36436 non-null  float64
 12  delay_carrier             36436 non-null  float64
 13  delay_weather             36436 non-null  float64
 14  delay_nas                 36436 non-null  float64
 15  delay_security            36436 non-null  float64
 16  delay_late_aircraft       36436 non-null  float64
dtypes: float64(10), object(7)
memory usage: 4.7+ MB

In [29]:
df.describe()

,flight_number,scheduled_elapsed_time,actual_elapsed_time,departure_delay,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
count,36436.000000,36436.000000,36436.000000,36436.000000,36436.000000,36436.000000,36436.000000,36436.000000,36436.000000,36436.000000
mean,1236.538424,219.732023,210.692776,9.081019,16.358382,6.025469,0.193325,2.336288,0.027198,3.201724
std,837.939412,84.268869,85.736409,44.915645,7.811675,34.719118,7.445406,13.106364,1.287493,17.067896
min,311.000000,67.000000,0.000000,-30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,521.000000,151.000000,144.000000,-7.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,938.000000,221.000000,217.000000,-3.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1715.000000,282.000000,279.000000,4.000000,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8819.000000,370.000000,497.000000,1118.000000,136.000000,1062.000000,845.000000,845.000000,121.000000,481.000000

In [30]:
df.shape

(36436, 17)

In [31]:
df["flight_date"] = pd.to_datetime(df["flight_date"], format= "%m/%d/%Y")

In [32]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,2025-01-01,311.0,N540US,KOA,15:59,16:07,340.0,334.0,8.0,16:22,15.0,0.0,0.0,0.0,0.0,0.0
1,DL,2025-01-01,320.0,N348DN,ATL,23:59,23:58,262.0,253.0,-1.0,00:32,34.0,0.0,0.0,0.0,0.0,0.0
2,DL,2025-01-01,327.0,N380DN,ATL,09:30,09:30,259.0,235.0,0.0,09:48,18.0,0.0,0.0,0.0,0.0,0.0
3,DL,2025-01-01,390.0,N542US,ATL,06:20,06:32,248.0,228.0,12.0,06:45,13.0,0.0,0.0,0.0,0.0,0.0
4,DL,2025-01-01,392.0,N705TW,DCA,08:09,08:05,291.0,263.0,-4.0,08:17,12.0,0.0,0.0,0.0,0.0,0.0

In [34]:
time_cols = [
    "scheduled_departure_time",
    "actual_departure_time",
    "wheels_off_time"
]
for cols in time_cols:
    df[cols] = df[cols].replace("24:00","00:00:00")
    df[cols] = df[cols].replace("24:00:00","00:00:00")
    df[cols] = df[cols].apply(lambda x: "0" + x if len(x)==4 else x)
    df[cols] = df[cols].apply(lambda x: x + ":00" if len(x)==5 else x)
    df[cols] = pd.to_datetime(df[cols],format="%H:%M:%S")

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36436 entries, 0 to 36435
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              36436 non-null  object
 1   flight_date               36436 non-null  datetime64[ns]
 2   flight_number             36436 non-null  float64
 3   tail_number               36436 non-null  object
 4   destination_airport       36436 non-null  object
 5   scheduled_departure_time  36436 non-null  datetime64[ns]
 6   actual_departure_time     36436 non-null  datetime64[ns]
 7   scheduled_elapsed_time    36436 non-null  float64
 8   actual_elapsed_time       36436 non-null  float64
 9   departure_delay           36436 non-null  float64
 10  wheels_off_time           36436 non-null  datetime64[ns]
 11  taxi_out_time             36436 non-null  float64
 12  delay_carrier             36436 non-null  float64
 13  delay_weather             36436 non-null  float64
 14  delay_nas                 36436 non-null  float64
 15  delay_security            36436 non-null  float64
 16  delay_late_aircraft       36436 non-null  float64
dtypes: datetime64[ns](4), float64(10), object(3)
memory usage: 4.7+ MB

In [36]:
float_cols = [
    "flight_number",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]
for cols in float_cols:
    df[cols] = df[cols].astype(int)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36436 entries, 0 to 36435
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              36436 non-null  object
 1   flight_date               36436 non-null  datetime64[ns]
 2   flight_number             36436 non-null  int64
 3   tail_number               36436 non-null  object
 4   destination_airport       36436 non-null  object
 5   scheduled_departure_time  36436 non-null  datetime64[ns]
 6   actual_departure_time     36436 non-null  datetime64[ns]
 7   scheduled_elapsed_time    36436 non-null  int64
 8   actual_elapsed_time       36436 non-null  int64
 9   departure_delay           36436 non-null  int64
 10  wheels_off_time           36436 non-null  datetime64[ns]
 11  taxi_out_time             36436 non-null  int64
 12  delay_carrier             36436 non-null  int64
 13  delay_weather             36436 non-null  int64
 14  delay_nas                 36436 non-null  int64
 15  delay_security            36436 non-null  int64
 16  delay_late_aircraft       36436 non-null  int64
dtypes: datetime64[ns](4), int64(10), object(3)
memory usage: 4.7+ MB

In [39]:
df["flight_date"] = df["flight_date"].dt.strftime("%Y-%m-%d")

In [40]:
for cols in time_cols:
    df[cols] = df[cols].dt.strftime("%H:%M:%S")

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36436 entries, 0 to 36435
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              36436 non-null  object
 1   flight_date               36436 non-null  object
 2   flight_number             36436 non-null  int64
 3   tail_number               36436 non-null  object
 4   destination_airport       36436 non-null  object
 5   scheduled_departure_time  36436 non-null  object
 6   actual_departure_time     36436 non-null  object
 7   scheduled_elapsed_time    36436 non-null  int64
 8   actual_elapsed_time       36436 non-null  int64
 9   departure_delay           36436 non-null  int64
 10  wheels_off_time           36436 non-null  object
 11  taxi_out_time             36436 non-null  int64
 12  delay_carrier             36436 non-null  int64
 13  delay_weather             36436 non-null  int64
 14  delay_nas                 36436 non-null  int64
 15  delay_security            36436 non-null  int64
 16  delay_late_aircraft       36436 non-null  int64
dtypes: int64(10), object(7)
memory usage: 4.7+ MB

In [42]:
df.isna().sum()

carrier_code                0
flight_date                 0
flight_number               0
tail_number                 0
destination_airport         0
scheduled_departure_time    0
actual_departure_time       0
scheduled_elapsed_time      0
actual_elapsed_time         0
departure_delay             0
wheels_off_time             0
taxi_out_time               0
delay_carrier               0
delay_weather               0
delay_nas                   0
delay_security              0
delay_late_aircraft         0
dtype: int64

In [43]:
df.to_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_clean\lax_cleaned.csv",index=False)