In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_raw\Detailed_Statistics_Departures_MSP.csv", skiprows=6)

In [4]:
df.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,DL,01/01/2025,312.0,N825NW,HNL,10:00,09:59,543.0,544.0,-1.0,10:23,24.0,0.0,0.0,0.0,0.0,0.0
1,DL,01/01/2025,342.0,N366NB,HDN,12:50,12:42,149.0,136.0,-8.0,12:56,14.0,0.0,0.0,0.0,0.0,0.0
2,DL,01/01/2025,377.0,N583DT,ANC,15:55,16:06,367.0,335.0,11.0,16:17,11.0,0.0,0.0,0.0,0.0,0.0
3,DL,01/01/2025,858.0,N353DN,SFO,18:48,18:48,266.0,261.0,0.0,19:14,26.0,0.0,0.0,0.0,0.0,0.0
4,DL,01/01/2025,868.0,N864DN,SEA,08:35,08:35,250.0,221.0,0.0,08:46,11.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66375 entries, 0 to 66374
Data columns (total 17 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Carrier Code                              66375 non-null  object
 1   Date (MM/DD/YYYY)                         66374 non-null  object
 2   Flight Number                             66374 non-null  float64
 3   Tail Number                               66374 non-null  object
 4   Destination Airport                       66374 non-null  object
 5   Scheduled departure time                  66374 non-null  object
 6   Actual departure time                     66374 non-null  object
 7   Scheduled elapsed time (Minutes)          66374 non-null  float64
 8   Actual elapsed time (Minutes)             66374 non-null  float64
 9   Departure delay (Minutes)                 66374 non-null  float64
 10  Wheels-off time                           66374 non-null  object
 11  Taxi-Out time (Minutes)                   66374 non-null  float64
 12  Delay Carrier (Minutes)                   66374 non-null  float64
 13  Delay Weather (Minutes)                   66374 non-null  float64
 14  Delay National Aviation System (Minutes)  66374 non-null  float64
 15  Delay Security (Minutes)                  66374 non-null  float64
 16  Delay Late Aircraft Arrival (Minutes)     66374 non-null  float64
dtypes: float64(10), object(7)
memory usage: 8.6+ MB

In [7]:
df.isna().sum()

Carrier Code                                0
Date (MM/DD/YYYY)                           1
Flight Number                               1
Tail Number                                 1
Destination Airport                         1
Scheduled departure time                    1
Actual departure time                       1
Scheduled elapsed time (Minutes)            1
Actual elapsed time (Minutes)               1
Departure delay (Minutes)                   1
Wheels-off time                             1
Taxi-Out time (Minutes)                     1
Delay Carrier (Minutes)                     1
Delay Weather (Minutes)                     1
Delay National Aviation System (Minutes)    1
Delay Security (Minutes)                    1
Delay Late Aircraft Arrival (Minutes)       1
dtype: int64

In [8]:
df.tail()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
66370,DL,12/31/2025,2972.0,N347NB,DFW,06:55,07:13,170.0,143.0,18.0,07:41,28.0,0.0,0.0,0.0,0.0,0.0
66371,DL,12/31/2025,2982.0,N357DN,BOI,12:09,12:07,189.0,201.0,-2.0,12:38,31.0,0.0,0.0,0.0,0.0,0.0
66372,DL,12/31/2025,2983.0,N324DU,DCA,10:29,10:26,148.0,150.0,-3.0,11:04,38.0,0.0,0.0,0.0,0.0,0.0
66373,DL,12/31/2025,3080.0,N337NB,JAC,11:25,11:21,155.0,201.0,-4.0,12:28,67.0,0.0,0.0,42.0,0.0,0.0
66374,SOURCE: Bureau of Transportation Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.dropna()

In [17]:
print(df.duplicated().sum())

0

In [18]:
df.columns = [
    "carrier_code",
    "flight_date",
    "flight_number",
    "tail_number",
    "destination_airport",
    "scheduled_departure_time",
    "actual_departure_time",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "wheels_off_time",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]

In [19]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,01/01/2025,312.0,N825NW,HNL,10:00,09:59,543.0,544.0,-1.0,10:23,24.0,0.0,0.0,0.0,0.0,0.0
1,DL,01/01/2025,342.0,N366NB,HDN,12:50,12:42,149.0,136.0,-8.0,12:56,14.0,0.0,0.0,0.0,0.0,0.0
2,DL,01/01/2025,377.0,N583DT,ANC,15:55,16:06,367.0,335.0,11.0,16:17,11.0,0.0,0.0,0.0,0.0,0.0
3,DL,01/01/2025,858.0,N353DN,SFO,18:48,18:48,266.0,261.0,0.0,19:14,26.0,0.0,0.0,0.0,0.0,0.0
4,DL,01/01/2025,868.0,N864DN,SEA,08:35,08:35,250.0,221.0,0.0,08:46,11.0,0.0,0.0,0.0,0.0,0.0

In [20]:
df["flight_date"] = pd.to_datetime(df["flight_date"], format = "%m/%d/%Y")

In [21]:
time_cols = [
    "scheduled_departure_time",
    "actual_departure_time",
    "wheels_off_time"
]
for col in time_cols:
    df[col] = df[col].replace("24:00","00:00:00")
    df[col] = df[col].replace("24:00:00","00:00:00")
    df[col] = df[col].apply(lambda x: "0" + x if len(x) == 4 else x)
    df[col] = df[col].apply(lambda x: x + ":00" if len(x) ==5 else x)
    df[col] = pd.to_datetime(df[col], format = "%H:%M:%S")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66374 entries, 0 to 66373
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              66374 non-null  object
 1   flight_date               66374 non-null  datetime64[ns]
 2   flight_number             66374 non-null  float64
 3   tail_number               66374 non-null  object
 4   destination_airport       66374 non-null  object
 5   scheduled_departure_time  66374 non-null  datetime64[ns]
 6   actual_departure_time     66374 non-null  datetime64[ns]
 7   scheduled_elapsed_time    66374 non-null  float64
 8   actual_elapsed_time       66374 non-null  float64
 9   departure_delay           66374 non-null  float64
 10  wheels_off_time           66374 non-null  datetime64[ns]
 11  taxi_out_time             66374 non-null  float64
 12  delay_carrier             66374 non-null  float64
 13  delay_weather             66374 non-null  float64
 14  delay_nas                 66374 non-null  float64
 15  delay_security            66374 non-null  float64
 16  delay_late_aircraft       66374 non-null  float64
dtypes: datetime64[ns](4), float64(10), object(3)
memory usage: 9.1+ MB

In [23]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,2025-01-01,312.0,N825NW,HNL,1900-01-01 10:00:00,1900-01-01 09:59:00,543.0,544.0,-1.0,1900-01-01 10:23:00,24.0,0.0,0.0,0.0,0.0,0.0
1,DL,2025-01-01,342.0,N366NB,HDN,1900-01-01 12:50:00,1900-01-01 12:42:00,149.0,136.0,-8.0,1900-01-01 12:56:00,14.0,0.0,0.0,0.0,0.0,0.0
2,DL,2025-01-01,377.0,N583DT,ANC,1900-01-01 15:55:00,1900-01-01 16:06:00,367.0,335.0,11.0,1900-01-01 16:17:00,11.0,0.0,0.0,0.0,0.0,0.0
3,DL,2025-01-01,858.0,N353DN,SFO,1900-01-01 18:48:00,1900-01-01 18:48:00,266.0,261.0,0.0,1900-01-01 19:14:00,26.0,0.0,0.0,0.0,0.0,0.0
4,DL,2025-01-01,868.0,N864DN,SEA,1900-01-01 08:35:00,1900-01-01 08:35:00,250.0,221.0,0.0,1900-01-01 08:46:00,11.0,0.0,0.0,0.0,0.0,0.0

In [24]:
float_cols = [
    "flight_number",
    "scheduled_elapsed_time",
    "actual_elapsed_time",
    "departure_delay",
    "taxi_out_time",
    "delay_carrier",
    "delay_weather",
    "delay_nas",
    "delay_security",
    "delay_late_aircraft"
]
for col in float_cols:
    df[col] = df[col].astype(int)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66374 entries, 0 to 66373
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              66374 non-null  object
 1   flight_date               66374 non-null  datetime64[ns]
 2   flight_number             66374 non-null  int64
 3   tail_number               66374 non-null  object
 4   destination_airport       66374 non-null  object
 5   scheduled_departure_time  66374 non-null  datetime64[ns]
 6   actual_departure_time     66374 non-null  datetime64[ns]
 7   scheduled_elapsed_time    66374 non-null  int64
 8   actual_elapsed_time       66374 non-null  int64
 9   departure_delay           66374 non-null  int64
 10  wheels_off_time           66374 non-null  datetime64[ns]
 11  taxi_out_time             66374 non-null  int64
 12  delay_carrier             66374 non-null  int64
 13  delay_weather             66374 non-null  int64
 14  delay_nas                 66374 non-null  int64
 15  delay_security            66374 non-null  int64
 16  delay_late_aircraft       66374 non-null  int64
dtypes: datetime64[ns](4), int64(10), object(3)
memory usage: 9.1+ MB

In [26]:
df["flight_date"] = df["flight_date"].dt.strftime("%Y-%m-%d")

In [27]:
for col in time_cols:
    df[col] = df[col].dt.strftime("%H:%M:%S")

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66374 entries, 0 to 66373
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   carrier_code              66374 non-null  object
 1   flight_date               66374 non-null  object
 2   flight_number             66374 non-null  int64
 3   tail_number               66374 non-null  object
 4   destination_airport       66374 non-null  object
 5   scheduled_departure_time  66374 non-null  object
 6   actual_departure_time     66374 non-null  object
 7   scheduled_elapsed_time    66374 non-null  int64
 8   actual_elapsed_time       66374 non-null  int64
 9   departure_delay           66374 non-null  int64
 10  wheels_off_time           66374 non-null  object
 11  taxi_out_time             66374 non-null  int64
 12  delay_carrier             66374 non-null  int64
 13  delay_weather             66374 non-null  int64
 14  delay_nas                 66374 non-null  int64
 15  delay_security            66374 non-null  int64
 16  delay_late_aircraft       66374 non-null  int64
dtypes: int64(10), object(7)
memory usage: 9.1+ MB

In [29]:
df.head()

,carrier_code,flight_date,flight_number,tail_number,destination_airport,scheduled_departure_time,actual_departure_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels_off_time,taxi_out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
0,DL,2025-01-01,312,N825NW,HNL,10:00:00,09:59:00,543,544,-1,10:23:00,24,0,0,0,0,0
1,DL,2025-01-01,342,N366NB,HDN,12:50:00,12:42:00,149,136,-8,12:56:00,14,0,0,0,0,0
2,DL,2025-01-01,377,N583DT,ANC,15:55:00,16:06:00,367,335,11,16:17:00,11,0,0,0,0,0
3,DL,2025-01-01,858,N353DN,SFO,18:48:00,18:48:00,266,261,0,19:14:00,26,0,0,0,0,0
4,DL,2025-01-01,868,N864DN,SEA,08:35:00,08:35:00,250,221,0,08:46:00,11,0,0,0,0,0

In [31]:
df.to_csv(r"C:\Users\justi\OneDrive\Desktop\delta_ops_project\data_clean\msp_cleaned.csv",index=False)